name: Deploy Vue.js App

on:
  push:
    branches:
      - main   # Production branch
      - develop # Development branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Build the Vue.js app
    - name: Install and Build Vue.js
      run: |
        set -x
        whoami
        echo "echoed whoami .. endeddd"
        nvm -v
        echo "echoed nvm -v .. endeddd"
        npm -v
        echo "echoed npm -v .. endeddd"